package ve.com.fsjv.devsicodetv.vistas;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author franklin
 */
public class FichaDetenidoDialog extends javax.swing.JDialog {

    /**
     * Creates new form vFichaDetenido
     */
    public FichaDetenidoDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panBarraHerramientas = new javax.swing.JToolBar();
        btnNuevo = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnAgregarCausa = new javax.swing.JButton();
        btnCelda = new javax.swing.JButton();
        btnEvidencias = new javax.swing.JButton();
        btnHuellas = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        panDatosPersonales = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCodigoInterno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCedulaIdentidad = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtAlias = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox();
        txtPasaporte = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbNacionalidad = new javax.swing.JComboBox();
        txtReligion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cmbEstadoCivil = new javax.swing.JComboBox();
        txtLugarNacimiento = new javax.swing.JTextField();
        txtDocumentoAnterior = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbReservista = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbAnio = new javax.swing.JComboBox();
        cmbMes = new javax.swing.JComboBox();
        cmbDia = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtAnio = new javax.swing.JFormattedTextField();
        panGaleria = new javax.swing.JPanel();
        panFoto1 = new javax.swing.JPanel();
        panDatosUbicacion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDireccionAnterior = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDireccionActual = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDireccionEmergencia = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtTelefonoCelular = new javax.swing.JFormattedTextField();
        txtTelefonoHabitacion = new javax.swing.JFormattedTextField();
        txtTelefonoEmergencia = new javax.swing.JFormattedTextField();
        panRasgosFisicos = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cmbColorPiel = new javax.swing.JComboBox();
        cmbColorOjos = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        cmbColorCabello = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        cmbTipoNariz = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        cmbLentes = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        cmbContextura = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        txtCicatriz = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtSeniasParticulares = new javax.swing.JTextField();
        txtEstatura = new javax.swing.JFormattedTextField();
        panInformacionAdicional = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        cmbVivienda = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        cmbTipoVivienda = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        cmbGradoInstruccion = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        txtProfesion = new javax.swing.JTextField();
        txtEstatusControl = new javax.swing.JTextField();
        btnCamara = new javax.swing.JButton();
        btnVerFoto = new javax.swing.JButton();
        btnGaleria = new javax.swing.JButton();
        btnVerHistoriales = new javax.swing.JButton();
        btnVerUltimosAgregados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panBarraHerramientas.setRollover(true);

        btnNuevo.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/new.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setToolTipText("Nuevo Registro");
        btnNuevo.setBorder(null);
        btnNuevo.setFocusable(false);
        btnNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNuevo.setMaximumSize(new java.awt.Dimension(55, 55));
        btnNuevo.setMinimumSize(new java.awt.Dimension(55, 55));
        btnNuevo.setPreferredSize(new java.awt.Dimension(55, 55));
        btnNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnNuevo);

        btnBuscar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/search.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setToolTipText("Buscar Registro");
        btnBuscar.setBorder(null);
        btnBuscar.setFocusable(false);
        btnBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuscar.setMaximumSize(new java.awt.Dimension(55, 55));
        btnBuscar.setMinimumSize(new java.awt.Dimension(55, 55));
        btnBuscar.setPreferredSize(new java.awt.Dimension(55, 55));
        btnBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnBuscar);

        btnGuardar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/save.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Guardar cambios");
        btnGuardar.setBorder(null);
        btnGuardar.setFocusable(false);
        btnGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGuardar.setMaximumSize(new java.awt.Dimension(55, 55));
        btnGuardar.setMinimumSize(new java.awt.Dimension(55, 55));
        btnGuardar.setPreferredSize(new java.awt.Dimension(55, 55));
        btnGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnGuardar);

        btnEditar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setToolTipText("Editar registro");
        btnEditar.setBorder(null);
        btnEditar.setFocusable(false);
        btnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEditar.setMaximumSize(new java.awt.Dimension(55, 55));
        btnEditar.setMinimumSize(new java.awt.Dimension(55, 55));
        btnEditar.setPreferredSize(new java.awt.Dimension(55, 55));
        btnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnEditar);

        btnBorrar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/delete.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.setToolTipText("Borrar registro");
        btnBorrar.setBorder(null);
        btnBorrar.setFocusable(false);
        btnBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrar.setMaximumSize(new java.awt.Dimension(55, 55));
        btnBorrar.setMinimumSize(new java.awt.Dimension(55, 55));
        btnBorrar.setPreferredSize(new java.awt.Dimension(55, 55));
        btnBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnBorrar);

        btnAgregarCausa.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnAgregarCausa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/add_causa.png"))); // NOI18N
        btnAgregarCausa.setText("Ag. Causa");
        btnAgregarCausa.setToolTipText("Agregar nueva causa de detencion");
        btnAgregarCausa.setBorder(null);
        btnAgregarCausa.setFocusable(false);
        btnAgregarCausa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCausa.setMaximumSize(new java.awt.Dimension(65, 55));
        btnAgregarCausa.setMinimumSize(new java.awt.Dimension(65, 55));
        btnAgregarCausa.setPreferredSize(new java.awt.Dimension(65, 55));
        btnAgregarCausa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnAgregarCausa);

        btnCelda.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnCelda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/carcel2.png"))); // NOI18N
        btnCelda.setText("Celda");
        btnCelda.setToolTipText("Asignar o cambiar celda ");
        btnCelda.setBorder(null);
        btnCelda.setFocusable(false);
        btnCelda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCelda.setMaximumSize(new java.awt.Dimension(55, 55));
        btnCelda.setMinimumSize(new java.awt.Dimension(55, 55));
        btnCelda.setPreferredSize(new java.awt.Dimension(55, 55));
        btnCelda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnCelda);

        btnEvidencias.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnEvidencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/pertenencias.png"))); // NOI18N
        btnEvidencias.setText("Evidencias");
        btnEvidencias.setToolTipText("Registrar evidencias");
        btnEvidencias.setBorder(null);
        btnEvidencias.setFocusable(false);
        btnEvidencias.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEvidencias.setMaximumSize(new java.awt.Dimension(70, 55));
        btnEvidencias.setMinimumSize(new java.awt.Dimension(70, 55));
        btnEvidencias.setPreferredSize(new java.awt.Dimension(70, 55));
        btnEvidencias.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnEvidencias);

        btnHuellas.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnHuellas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/huella.png"))); // NOI18N
        btnHuellas.setText("Huellas");
        btnHuellas.setToolTipText("Registrar huellas dactilares");
        btnHuellas.setBorder(null);
        btnHuellas.setFocusable(false);
        btnHuellas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuellas.setMaximumSize(new java.awt.Dimension(55, 55));
        btnHuellas.setMinimumSize(new java.awt.Dimension(55, 55));
        btnHuellas.setPreferredSize(new java.awt.Dimension(55, 55));
        btnHuellas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnHuellas);

        btnImprimir.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/print.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setToolTipText("Imprimir ficha del detenido");
        btnImprimir.setBorder(null);
        btnImprimir.setFocusable(false);
        btnImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImprimir.setMaximumSize(new java.awt.Dimension(55, 55));
        btnImprimir.setMinimumSize(new java.awt.Dimension(55, 55));
        btnImprimir.setPreferredSize(new java.awt.Dimension(55, 55));
        btnImprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnImprimir);

        btnCancelar.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Cancelar operacion");
        btnCancelar.setBorder(null);
        btnCancelar.setFocusable(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setMaximumSize(new java.awt.Dimension(60, 55));
        btnCancelar.setMinimumSize(new java.awt.Dimension(60, 55));
        btnCancelar.setPreferredSize(new java.awt.Dimension(60, 55));
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnCancelar);

        panDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos Personales", 1, 0, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        panDatosPersonales.setPreferredSize(new java.awt.Dimension(469, 367));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel1.setText("Numero de Control:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel2.setText("Nombre(s):");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel3.setText("Apellido(s):");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setText("Alias:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel5.setText("Nro  de Pasaporte:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel6.setText("Religion:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel7.setText("Fecha de Nac.:");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel8.setText("Lugar de Nac.:");

        txtCodigoInterno.setEditable(false);
        txtCodigoInterno.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoInterno.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtCodigoInterno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel11.setText("Cedula de Identidad:");

        txtCedulaIdentidad.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtCedulaIdentidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        txtNombres.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        txtApellidos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        txtAlias.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtAlias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel12.setText("Sexo:");

        cmbSexo.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Femenino", "Masculino" }));
        cmbSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        cmbSexo.setLightWeightPopupEnabled(false);

        txtPasaporte.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtPasaporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel13.setText("Nacionalidad:");

        cmbNacionalidad.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbNacionalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Venezolano", "Extrangero", "Residente", "Otra Nacionalidad" }));
        cmbNacionalidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        txtReligion.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtReligion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel14.setText("Estado Civil:");

        cmbEstadoCivil.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Casado", "Concubino", "Divorciado", "Soltero", "Viudo" }));
        cmbEstadoCivil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        txtLugarNacimiento.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtLugarNacimiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        txtDocumentoAnterior.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtDocumentoAnterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel9.setText("Docu. Anterior:");

        cmbReservista.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbReservista.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Si", "No" }));
        cmbReservista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel10.setText("Reservista:");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel16.setText("Año:");

        cmbAnio.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año" }));
        cmbAnio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        cmbMes.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes" }));
        cmbMes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        cmbMes.setEnabled(false);

        cmbDia.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dia" }));
        cmbDia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        cmbDia.setEnabled(false);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel15.setText("Edad:");

        txtEdad.setEditable(false);
        txtEdad.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        txtAnio.setEditable(false);
        try {
            txtAnio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtAnio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtAnio.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        javax.swing.GroupLayout panDatosPersonalesLayout = new javax.swing.GroupLayout(panDatosPersonales);
        panDatosPersonales.setLayout(panDatosPersonalesLayout);
        panDatosPersonalesLayout.setHorizontalGroup(
            panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(cmbReservista, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addComponent(txtCodigoInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCedulaIdentidad))
                    .addComponent(txtNombres)
                    .addComponent(txtApellidos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(cmbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtLugarNacimiento)
                    .addComponent(txtDocumentoAnterior)
                    .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                                .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbEstadoCivil, 0, 107, Short.MAX_VALUE)
                            .addComponent(txtEdad))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panDatosPersonalesLayout.setVerticalGroup(
            panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigoInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtCedulaIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlias, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(cmbSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(cmbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtReligion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(cmbEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtLugarNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocumentoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbReservista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel16)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panGaleria.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Galeria de Fotos", 1, 0, new java.awt.Font("Arial", 1, 12), java.awt.Color.black)); // NOI18N
        panGaleria.setPreferredSize(new java.awt.Dimension(526, 123));

        panFoto1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panFoto1Layout = new javax.swing.GroupLayout(panFoto1);
        panFoto1.setLayout(panFoto1Layout);
        panFoto1Layout.setHorizontalGroup(
            panFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panFoto1Layout.setVerticalGroup(
            panFoto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 88, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panGaleriaLayout = new javax.swing.GroupLayout(panGaleria);
        panGaleria.setLayout(panGaleriaLayout);
        panGaleriaLayout.setHorizontalGroup(
            panGaleriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGaleriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panGaleriaLayout.setVerticalGroup(
            panGaleriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGaleriaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panDatosUbicacion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos de Ubicacion", 1, 0, new java.awt.Font("Arial", 1, 12), java.awt.Color.black)); // NOI18N

        txtDireccionAnterior.setColumns(20);
        txtDireccionAnterior.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtDireccionAnterior.setRows(5);
        txtDireccionAnterior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jScrollPane1.setViewportView(txtDireccionAnterior);

        txtDireccionActual.setColumns(20);
        txtDireccionActual.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtDireccionActual.setRows(5);
        txtDireccionActual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jScrollPane2.setViewportView(txtDireccionActual);

        txtDireccionEmergencia.setColumns(20);
        txtDireccionEmergencia.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtDireccionEmergencia.setRows(5);
        txtDireccionEmergencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        jScrollPane3.setViewportView(txtDireccionEmergencia);

        jLabel26.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel26.setText("Direccion Actual de Habitacion:");

        jLabel27.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel27.setText("Direccion Anterior de Habitacion:");

        jLabel28.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel28.setText("Direccion de Emergencia:");

        jLabel29.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel29.setText("Telefono Celular:");

        jLabel30.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel30.setText("Telefono de Emergencia:");

        jLabel31.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel31.setText("Telefono de Habitacion:");

        txtTelefonoCelular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        try {
            txtTelefonoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(####)-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtTelefonoHabitacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        try {
            txtTelefonoHabitacion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(####)-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtTelefonoEmergencia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        try {
            txtTelefonoEmergencia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(####)-#######")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panDatosUbicacionLayout = new javax.swing.GroupLayout(panDatosUbicacion);
        panDatosUbicacion.setLayout(panDatosUbicacionLayout);
        panDatosUbicacionLayout.setHorizontalGroup(
            panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefonoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31)
                    .addComponent(jLabel30))
                .addContainerGap())
        );
        panDatosUbicacionLayout.setVerticalGroup(
            panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panDatosUbicacionLayout.createSequentialGroup()
                .addGroup(panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panDatosUbicacionLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(txtTelefonoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panDatosUbicacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(panDatosUbicacionLayout.createSequentialGroup()
                                    .addComponent(jLabel29)
                                    .addGap(11, 11, 11)
                                    .addComponent(txtTelefonoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel26))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panDatosUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panDatosUbicacionLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTelefonoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel28)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panRasgosFisicos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Rasgos Fisicos y Señas Particulares", 1, 0, new java.awt.Font("Arial", 1, 12), java.awt.Color.black)); // NOI18N

        jLabel17.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel17.setText("Color de Piel:");

        cmbColorPiel.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbColorPiel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Morena", "Negro", "Blanca", "Amarillo" }));
        cmbColorPiel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        cmbColorOjos.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbColorOjos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Azul Claro", "Verde Claro", "Gris", "Negro", "Cafe", "Castaño", "Marrones" }));
        cmbColorOjos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel18.setText("Color de Ojos:");

        cmbColorCabello.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbColorCabello.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Negro", "Blanco", "Amarillo", "Castaño Oscuro", "Castaño Claro", "Oscuro", "Gris" }));
        cmbColorCabello.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel19.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel19.setText("Color de Cabello:");

        cmbTipoNariz.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbTipoNariz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Chata", "Corta", "Larga", "Pequeña", "Perfilada", "Aguileña" }));
        cmbTipoNariz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel20.setText("Tipo de Nariz:");

        jLabel21.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel21.setText("Estatura:");

        jLabel22.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel22.setText("Lentes:");

        cmbLentes.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbLentes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Si", "No" }));
        cmbLentes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel23.setText("Contextura:");

        cmbContextura.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbContextura.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Ectoformos (delgados)", "Mesoformos (Moderados)", "Endoformos (Obesos)" }));
        cmbContextura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel24.setText("Cicatriz:");

        txtCicatriz.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtCicatriz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel25.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel25.setText("Señas Part.:");

        txtSeniasParticulares.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtSeniasParticulares.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        try {
            txtEstatura.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#.##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtEstatura.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout panRasgosFisicosLayout = new javax.swing.GroupLayout(panRasgosFisicos);
        panRasgosFisicos.setLayout(panRasgosFisicosLayout);
        panRasgosFisicosLayout.setHorizontalGroup(
            panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRasgosFisicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addGap(22, 22, 22)
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panRasgosFisicosLayout.createSequentialGroup()
                        .addComponent(cmbColorCabello, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel20))
                    .addGroup(panRasgosFisicosLayout.createSequentialGroup()
                        .addComponent(cmbColorPiel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panRasgosFisicosLayout.createSequentialGroup()
                        .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(cmbLentes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbTipoNariz, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbColorOjos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCicatriz))
                .addGap(18, 18, 18)
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panRasgosFisicosLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panRasgosFisicosLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(14, 14, 14)))
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbContextura, 0, 191, Short.MAX_VALUE)
                    .addComponent(txtSeniasParticulares))
                .addContainerGap())
        );
        panRasgosFisicosLayout.setVerticalGroup(
            panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panRasgosFisicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbColorPiel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(cmbLentes, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(cmbColorOjos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(cmbContextura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstatura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(panRasgosFisicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbColorCabello, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel24)
                    .addComponent(txtCicatriz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtSeniasParticulares, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipoNariz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panInformacionAdicional.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informacion Adicional", 0, 0, new java.awt.Font("Arial", 1, 12), java.awt.Color.black)); // NOI18N

        jLabel32.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel32.setText("Vivienda:");

        cmbVivienda.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbVivienda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Si", "No" }));
        cmbVivienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel33.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel33.setText("Tipo:");

        cmbTipoVivienda.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbTipoVivienda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Casa", "Apartamento", "Habitacion", "Cuarto", "Rancho", "Finca" }));
        cmbTipoVivienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel34.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel34.setText("Grado de Instruccion:");

        cmbGradoInstruccion.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        cmbGradoInstruccion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "---", "Analfabeta", "Bachiller", "Educacion Basica", "Primaria", "Secundaria", "Universitario (TSU Licdos Ing otros)", "Especializacion", "Doctorado" }));
        cmbGradoInstruccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        jLabel35.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel35.setText("Profesion:");

        txtProfesion.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        txtProfesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));

        javax.swing.GroupLayout panInformacionAdicionalLayout = new javax.swing.GroupLayout(panInformacionAdicional);
        panInformacionAdicional.setLayout(panInformacionAdicionalLayout);
        panInformacionAdicionalLayout.setHorizontalGroup(
            panInformacionAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInformacionAdicionalLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(18, 18, 18)
                .addComponent(cmbGradoInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel35)
                .addGap(18, 18, 18)
                .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panInformacionAdicionalLayout.setVerticalGroup(
            panInformacionAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInformacionAdicionalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panInformacionAdicionalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(cmbVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(cmbTipoVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(cmbGradoInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtEstatusControl.setEditable(false);
        txtEstatusControl.setBackground(new java.awt.Color(175, 221, 233));
        txtEstatusControl.setFont(new java.awt.Font("Arial", 1, 32)); // NOI18N
        txtEstatusControl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstatusControl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)));
        txtEstatusControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstatusControlActionPerformed(evt);
            }
        });

        btnCamara.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnCamara.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/camera.png"))); // NOI18N
        btnCamara.setToolTipText("Tomar Foto");
        btnCamara.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCamara.setFocusPainted(false);
        btnCamara.setFocusable(false);
        btnCamara.setMaximumSize(new java.awt.Dimension(42, 37));
        btnCamara.setMinimumSize(new java.awt.Dimension(42, 37));
        btnCamara.setPreferredSize(new java.awt.Dimension(42, 37));

        btnVerFoto.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnVerFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/ver.png"))); // NOI18N
        btnVerFoto.setToolTipText("Ver Foto");
        btnVerFoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnVerFoto.setFocusPainted(false);
        btnVerFoto.setFocusable(false);
        btnVerFoto.setMaximumSize(new java.awt.Dimension(42, 37));
        btnVerFoto.setMinimumSize(new java.awt.Dimension(42, 37));
        btnVerFoto.setPreferredSize(new java.awt.Dimension(42, 37));

        btnGaleria.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnGaleria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/gallery-2-small.png"))); // NOI18N
        btnGaleria.setToolTipText("Ver Galeria");
        btnGaleria.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnGaleria.setMaximumSize(new java.awt.Dimension(42, 37));
        btnGaleria.setMinimumSize(new java.awt.Dimension(42, 37));
        btnGaleria.setPreferredSize(new java.awt.Dimension(42, 37));

        btnVerHistoriales.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnVerHistoriales.setText("Ver Historiales");
        btnVerHistoriales.setToolTipText("Ver Historiales");
        btnVerHistoriales.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnVerUltimosAgregados.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnVerUltimosAgregados.setText("Ver Ultimos Agregados");
        btnVerUltimosAgregados.setToolTipText("Ver Ultimos Registros Agregados");
        btnVerUltimosAgregados.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBarraHerramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panDatosUbicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panGaleria, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtEstatusControl)
                                        .addGap(4, 4, 4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnCamara, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnGaleria, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnVerHistoriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnVerUltimosAgregados, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(panRasgosFisicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panInformacionAdicional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panBarraHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnGaleria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnVerFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnVerHistoriales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnVerUltimosAgregados, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnCamara, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(10, 10, 10)
                                .addComponent(txtEstatusControl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panGaleria, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panDatosUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panRasgosFisicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panInformacionAdicional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtEstatusControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstatusControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstatusControlActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCausa;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCamara;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCelda;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEvidencias;
    private javax.swing.JButton btnGaleria;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnHuellas;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVerFoto;
    private javax.swing.JButton btnVerHistoriales;
    private javax.swing.JButton btnVerUltimosAgregados;
    private javax.swing.JComboBox cmbAnio;
    private javax.swing.JComboBox cmbColorCabello;
    private javax.swing.JComboBox cmbColorOjos;
    private javax.swing.JComboBox cmbColorPiel;
    private javax.swing.JComboBox cmbContextura;
    private javax.swing.JComboBox cmbDia;
    private javax.swing.JComboBox cmbEstadoCivil;
    private javax.swing.JComboBox cmbGradoInstruccion;
    private javax.swing.JComboBox cmbLentes;
    private javax.swing.JComboBox cmbMes;
    private javax.swing.JComboBox cmbNacionalidad;
    private javax.swing.JComboBox cmbReservista;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JComboBox cmbTipoNariz;
    private javax.swing.JComboBox cmbTipoVivienda;
    private javax.swing.JComboBox cmbVivienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JToolBar panBarraHerramientas;
    public javax.swing.JPanel panDatosPersonales;
    public javax.swing.JPanel panDatosUbicacion;
    private javax.swing.JPanel panFoto1;
    public javax.swing.JPanel panGaleria;
    public javax.swing.JPanel panInformacionAdicional;
    public javax.swing.JPanel panRasgosFisicos;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JFormattedTextField txtAnio;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCedulaIdentidad;
    private javax.swing.JTextField txtCicatriz;
    private javax.swing.JTextField txtCodigoInterno;
    private javax.swing.JTextArea txtDireccionActual;
    private javax.swing.JTextArea txtDireccionAnterior;
    private javax.swing.JTextArea txtDireccionEmergencia;
    private javax.swing.JTextField txtDocumentoAnterior;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JFormattedTextField txtEstatura;
    private javax.swing.JTextField txtEstatusControl;
    private javax.swing.JTextField txtLugarNacimiento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPasaporte;
    private javax.swing.JTextField txtProfesion;
    private javax.swing.JTextField txtReligion;
    private javax.swing.JTextField txtSeniasParticulares;
    private javax.swing.JFormattedTextField txtTelefonoCelular;
    private javax.swing.JFormattedTextField txtTelefonoEmergencia;
    private javax.swing.JFormattedTextField txtTelefonoHabitacion;
    // End of variables declaration//GEN-END:variables

    public JFormattedTextField getTxtAnio() {
        return txtAnio;
    }

    public void setTxtAnio(JFormattedTextField txtAnio) {
        this.txtAnio = txtAnio;
    }

    public JFormattedTextField getTxtEstatura() {
        return txtEstatura;
    }

    public void setTxtEstatura(JFormattedTextField txtEstatura) {
        this.txtEstatura = txtEstatura;
    }

    public JComboBox getCmbAnio() {
        return cmbAnio;
    }

    public void setCmbAnio(JComboBox cmbAnio) {
        this.cmbAnio = cmbAnio;
    }

    public JComboBox getCmbDia() {
        return cmbDia;
    }

    public void setCmbDia(JComboBox cmbDia) {
        this.cmbDia = cmbDia;
    }

    public JComboBox getCmbMes() {
        return cmbMes;
    }

    public void setCmbMes(JComboBox cmbMes) {
        this.cmbMes = cmbMes;
    }

    public JTextField getTxtEdad() {
        return txtEdad;
    }

    public void setTxtEdad(JTextField txtEdad) {
        this.txtEdad = txtEdad;
    }

    public JButton getBtnAgregarCausa() {
        return btnAgregarCausa;
    }

    public void setBtnAgregarCausa(JButton btnAgregarCausa) {
        this.btnAgregarCausa = btnAgregarCausa;
    }

    public JButton getBtnBorrar() {
        return btnBorrar;
    }

    public void setBtnBorrar(JButton btnBorrar) {
        this.btnBorrar = btnBorrar;
    }

    public JButton getBtnBuscar() {
        return btnBuscar;
    }

    public void setBtnBuscar(JButton btnBuscar) {
        this.btnBuscar = btnBuscar;
    }

    public JButton getBtnCamara() {
        return btnCamara;
    }

    public void setBtnCamara(JButton btnCamara) {
        this.btnCamara = btnCamara;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnCelda() {
        return btnCelda;
    }

    public void setBtnCelda(JButton btnCelda) {
        this.btnCelda = btnCelda;
    }

    public JButton getBtnEditar() {
        return btnEditar;
    }

    public void setBtnEditar(JButton btnEditar) {
        this.btnEditar = btnEditar;
    }

    public JButton getBtnEvidencias() {
        return btnEvidencias;
    }

    public void setBtnEvidencias(JButton btnEvidencias) {
        this.btnEvidencias = btnEvidencias;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JButton getBtnHuellas() {
        return btnHuellas;
    }

    public void setBtnHuellas(JButton btnHuellas) {
        this.btnHuellas = btnHuellas;
    }

    public JButton getBtnImprimir() {
        return btnImprimir;
    }

    public void setBtnImprimir(JButton btnImprimir) {
        this.btnImprimir = btnImprimir;
    }

    public JButton getBtnNuevo() {
        return btnNuevo;
    }

    public void setBtnNuevo(JButton btnNuevo) {
        this.btnNuevo = btnNuevo;
    }

    public JButton getBtnVerFoto() {
        return btnVerFoto;
    }

    public void setBtnVerFoto(JButton btnVerFoto) {
        this.btnVerFoto = btnVerFoto;
    }

    public JButton getBtnVerHistoriales() {
        return btnVerHistoriales;
    }

    public void setBtnVerHistoriales(JButton btnVerHistoriales) {
        this.btnVerHistoriales = btnVerHistoriales;
    }

    public JButton getBtnVerUltimosAgregados() {
        return btnVerUltimosAgregados;
    }

    public void setBtnVerUltimosAgregados(JButton btnVerUltimosAgregados) {
        this.btnVerUltimosAgregados = btnVerUltimosAgregados;
    }

    public JComboBox getCmbColorCabello() {
        return cmbColorCabello;
    }

    public void setCmbColorCabello(JComboBox cmbColorCabello) {
        this.cmbColorCabello = cmbColorCabello;
    }

    public JComboBox getCmbColorOjos() {
        return cmbColorOjos;
    }

    public void setCmbColorOjos(JComboBox cmbColorOjos) {
        this.cmbColorOjos = cmbColorOjos;
    }

    public JComboBox getCmbColorPiel() {
        return cmbColorPiel;
    }

    public void setCmbColorPiel(JComboBox cmbColorPiel) {
        this.cmbColorPiel = cmbColorPiel;
    }

    public JComboBox getCmbContextura() {
        return cmbContextura;
    }

    public void setCmbContextura(JComboBox cmbContextura) {
        this.cmbContextura = cmbContextura;
    }

    public JComboBox getCmbEstadoCivil() {
        return cmbEstadoCivil;
    }

    public void setCmbEstadoCivil(JComboBox cmbEstadoCivil) {
        this.cmbEstadoCivil = cmbEstadoCivil;
    }

    public JComboBox getCmbGradoInstruccion() {
        return cmbGradoInstruccion;
    }

    public void setCmbGradoInstruccion(JComboBox cmbGradoInstruccion) {
        this.cmbGradoInstruccion = cmbGradoInstruccion;
    }

    public JComboBox getCmbLentes() {
        return cmbLentes;
    }

    public void setCmbLentes(JComboBox cmbLentes) {
        this.cmbLentes = cmbLentes;
    }

    public JComboBox getCmbNacionalidad() {
        return cmbNacionalidad;
    }

    public void setCmbNacionalidad(JComboBox cmbNacionalidad) {
        this.cmbNacionalidad = cmbNacionalidad;
    }

    public JComboBox getCmbReservista() {
        return cmbReservista;
    }

    public void setCmbReservista(JComboBox cmbReservista) {
        this.cmbReservista = cmbReservista;
    }

    public JComboBox getCmbSexo() {
        return cmbSexo;
    }

    public void setCmbSexo(JComboBox cmbSexo) {
        this.cmbSexo = cmbSexo;
    }

    public JComboBox getCmbTipoNariz() {
        return cmbTipoNariz;
    }

    public void setCmbTipoNariz(JComboBox cmbTipoNariz) {
        this.cmbTipoNariz = cmbTipoNariz;
    }

    public JComboBox getCmbTipoVivienda() {
        return cmbTipoVivienda;
    }

    public void setCmbTipoVivienda(JComboBox cmbTipoVivienda) {
        this.cmbTipoVivienda = cmbTipoVivienda;
    }

    public JComboBox getCmbVivienda() {
        return cmbVivienda;
    }

    public void setCmbVivienda(JComboBox cmbVivienda) {
        this.cmbVivienda = cmbVivienda;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public void setjScrollPane2(JScrollPane jScrollPane2) {
        this.jScrollPane2 = jScrollPane2;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    public void setjScrollPane3(JScrollPane jScrollPane3) {
        this.jScrollPane3 = jScrollPane3;
    }

    public JPanel getPanFoto1() {
        return panFoto1;
    }

    public void setPanFoto1(JPanel panFoto1) {
        this.panFoto1 = panFoto1;
    }

    public JTextField getTxtAlias() {
        return txtAlias;
    }

    public void setTxtAlias(JTextField txtAlias) {
        this.txtAlias = txtAlias;
    }

    public JTextField getTxtApellidos() {
        return txtApellidos;
    }

    public void setTxtApellidos(JTextField txtApellidos) {
        this.txtApellidos = txtApellidos;
    }

    public JTextField getTxtCedulaIdentidad() {
        return txtCedulaIdentidad;
    }

    public void setTxtCedulaIdentidad(JTextField txtCedulaIdentidad) {
        this.txtCedulaIdentidad = txtCedulaIdentidad;
    }

    public JTextField getTxtCicatriz() {
        return txtCicatriz;
    }

    public void setTxtCicatriz(JTextField txtCicatriz) {
        this.txtCicatriz = txtCicatriz;
    }

    public JTextField getTxtCodigoInterno() {
        return txtCodigoInterno;
    }

    public void setTxtCodigoInterno(JTextField txtCodigoInterno) {
        this.txtCodigoInterno = txtCodigoInterno;
    }

    public JTextArea getTxtDireccionActual() {
        return txtDireccionActual;
    }

    public void setTxtDireccionActual(JTextArea txtDireccionActual) {
        this.txtDireccionActual = txtDireccionActual;
    }

    public JTextArea getTxtDireccionAnterior() {
        return txtDireccionAnterior;
    }

    public void setTxtDireccionAnterior(JTextArea txtDireccionAnterior) {
        this.txtDireccionAnterior = txtDireccionAnterior;
    }

    public JTextArea getTxtDireccionEmergencia() {
        return txtDireccionEmergencia;
    }

    public void setTxtDireccionEmergencia(JTextArea txtDireccionEmergencia) {
        this.txtDireccionEmergencia = txtDireccionEmergencia;
    }

    public JTextField getTxtDocumentoAnterior() {
        return txtDocumentoAnterior;
    }

    public void setTxtDocumentoAnterior(JTextField txtDocumentoAnterior) {
        this.txtDocumentoAnterior = txtDocumentoAnterior;
    }

    public JTextField getTxtEstatusControl() {
        return txtEstatusControl;
    }

    public void setTxtEstatusControl(JTextField txtEstatusControl) {
        this.txtEstatusControl = txtEstatusControl;
    }

    public JTextField getTxtLugarNacimiento() {
        return txtLugarNacimiento;
    }

    public void setTxtLugarNacimiento(JTextField txtLugarNacimiento) {
        this.txtLugarNacimiento = txtLugarNacimiento;
    }

    public JTextField getTxtNombres() {
        return txtNombres;
    }

    public void setTxtNombres(JTextField txtNombres) {
        this.txtNombres = txtNombres;
    }

    public JTextField getTxtPasaporte() {
        return txtPasaporte;
    }

    public void setTxtPasaporte(JTextField txtPasaporte) {
        this.txtPasaporte = txtPasaporte;
    }

    public JTextField getTxtProfesion() {
        return txtProfesion;
    }

    public void setTxtProfesion(JTextField txtProfesion) {
        this.txtProfesion = txtProfesion;
    }

    public JTextField getTxtReligion() {
        return txtReligion;
    }

    public void setTxtReligion(JTextField txtReligion) {
        this.txtReligion = txtReligion;
    }

    public JTextField getTxtSeniasParticulares() {
        return txtSeniasParticulares;
    }

    public void setTxtSeniasParticulares(JTextField txtSeniasParticulares) {
        this.txtSeniasParticulares = txtSeniasParticulares;
    }

    public JFormattedTextField getTxtTelefonoCelular() {
        return txtTelefonoCelular;
    }

    public void setTxtTelefonoCelular(JFormattedTextField txtTelefonoCelular) {
        this.txtTelefonoCelular = txtTelefonoCelular;
    }

    public JFormattedTextField getTxtTelefonoEmergencia() {
        return txtTelefonoEmergencia;
    }

    public void setTxtTelefonoEmergencia(JFormattedTextField txtTelefonoEmergencia) {
        this.txtTelefonoEmergencia = txtTelefonoEmergencia;
    }

    public JFormattedTextField getTxtTelefonoHabitacion() {
        return txtTelefonoHabitacion;
    }

    public void setTxtTelefonoHabitacion(JFormattedTextField txtTelefonoHabitacion) {
        this.txtTelefonoHabitacion = txtTelefonoHabitacion;
    }
}
