/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ve.com.fsjv.devsicodetv.vistas;

import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JToolBar;

/**
 *
 * @author Juan
 */
public class GaleriaFotosDialog extends javax.swing.JDialog {

    /**
     * Creates new form ListaFotosDialog
     */
    public GaleriaFotosDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fotoPanel = new javax.swing.JLabel();
        panBarraHerramientas = new javax.swing.JToolBar();
        btnPrimero = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnUltima = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        labelTituloFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        fotoPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        panBarraHerramientas.setRollover(true);

        btnPrimero.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnPrimero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/prev.png"))); // NOI18N
        btnPrimero.setToolTipText("Ir al inicio");
        btnPrimero.setFocusPainted(false);
        btnPrimero.setFocusable(false);
        btnPrimero.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrimero.setMaximumSize(new java.awt.Dimension(42, 37));
        btnPrimero.setMinimumSize(new java.awt.Dimension(42, 37));
        btnPrimero.setPreferredSize(new java.awt.Dimension(42, 37));
        btnPrimero.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnPrimero);

        btnAtras.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/first.png"))); // NOI18N
        btnAtras.setToolTipText("Atras");
        btnAtras.setFocusPainted(false);
        btnAtras.setFocusable(false);
        btnAtras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAtras.setMaximumSize(new java.awt.Dimension(42, 37));
        btnAtras.setMinimumSize(new java.awt.Dimension(42, 37));
        btnAtras.setPreferredSize(new java.awt.Dimension(42, 37));
        btnAtras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnAtras);

        btnSiguiente.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/last.png"))); // NOI18N
        btnSiguiente.setToolTipText("Siguiente");
        btnSiguiente.setFocusPainted(false);
        btnSiguiente.setFocusable(false);
        btnSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSiguiente.setMaximumSize(new java.awt.Dimension(42, 37));
        btnSiguiente.setMinimumSize(new java.awt.Dimension(42, 37));
        btnSiguiente.setPreferredSize(new java.awt.Dimension(42, 37));
        btnSiguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnSiguiente);

        btnUltima.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        btnUltima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utilitarios/imgs/next.png"))); // NOI18N
        btnUltima.setToolTipText("ir al final");
        btnUltima.setFocusPainted(false);
        btnUltima.setFocusable(false);
        btnUltima.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUltima.setMaximumSize(new java.awt.Dimension(42, 37));
        btnUltima.setMinimumSize(new java.awt.Dimension(42, 37));
        btnUltima.setPreferredSize(new java.awt.Dimension(42, 37));
        btnUltima.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        panBarraHerramientas.add(btnUltima);
        panBarraHerramientas.add(filler1);

        labelTituloFoto.setText("jLabel1");
        panBarraHerramientas.add(labelTituloFoto);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panBarraHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panBarraHerramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GaleriaFotosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GaleriaFotosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GaleriaFotosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GaleriaFotosDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GaleriaFotosDialog dialog = new GaleriaFotosDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public JButton getBtnAtras() {
        return btnAtras;
    }

    public void setBtnAtras(JButton btnAtras) {
        this.btnAtras = btnAtras;
    }

    public JButton getBtnPrimero() {
        return btnPrimero;
    }

    public void setBtnPrimero(JButton btnPrimero) {
        this.btnPrimero = btnPrimero;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JButton getBtnUltima() {
        return btnUltima;
    }

    public void setBtnUltima(JButton btnUltima) {
        this.btnUltima = btnUltima;
    }

    public Box.Filler getFiller1() {
        return filler1;
    }

    public void setFiller1(Box.Filler filler1) {
        this.filler1 = filler1;
    }

    public JLabel getFotoPanel() {
        return fotoPanel;
    }

    public void setFotoPanel(JLabel fotoPanel) {
        this.fotoPanel = fotoPanel;
    }

    public JLabel getLabelTituloFoto() {
        return labelTituloFoto;
    }

    public void setLabelTituloFoto(JLabel labelTituloFoto) {
        this.labelTituloFoto = labelTituloFoto;
    }

    public JToolBar getPanBarraHerramientas() {
        return panBarraHerramientas;
    }

    public void setPanBarraHerramientas(JToolBar panBarraHerramientas) {
        this.panBarraHerramientas = panBarraHerramientas;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnPrimero;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltima;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel fotoPanel;
    private javax.swing.JLabel labelTituloFoto;
    private javax.swing.JToolBar panBarraHerramientas;
    // End of variables declaration//GEN-END:variables
}
