/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ve.com.fsjv.devsicodetv.views;

import javax.swing.JButton;

/**
 *
 * @author family-sj
 */
public class VisitDialog extends javax.swing.JDialog {

    /**
     * Creates new form VisitDialog
     */
    public VisitDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNew = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnFindArrested = new javax.swing.JButton();
        btnAddVisitor = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPending = new javax.swing.JButton();
        btnLastAdded = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/Files-New-File-icon.png"))); // NOI18N
        btnNew.setToolTipText("Nuevo registro");
        btnNew.setBorderPainted(false);
        btnNew.setFocusable(false);
        btnNew.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNew.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnNew);

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/folder-open-icon.png"))); // NOI18N
        btnOpen.setToolTipText("Buscar");
        btnOpen.setBorderPainted(false);
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnOpen);

        btnFindArrested.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/user-check-icon.png"))); // NOI18N
        btnFindArrested.setToolTipText("Buscar detenido");
        btnFindArrested.setBorderPainted(false);
        btnFindArrested.setFocusable(false);
        btnFindArrested.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFindArrested.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnFindArrested);

        btnAddVisitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/Actions-user-group-new-icon.png"))); // NOI18N
        btnAddVisitor.setToolTipText("Agregar visitante");
        btnAddVisitor.setBorderPainted(false);
        btnAddVisitor.setFocusable(false);
        btnAddVisitor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddVisitor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnAddVisitor);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/Actions-document-save-icon.png"))); // NOI18N
        btnSave.setToolTipText("Guardar cambios");
        btnSave.setBorderPainted(false);
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSave);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/Actions-document-edit-icon.png"))); // NOI18N
        btnEdit.setToolTipText("Editar registro");
        btnEdit.setBorderPainted(false);
        btnEdit.setFocusable(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnEdit);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/delete-file-icon.png"))); // NOI18N
        btnDelete.setToolTipText("Borrar registro");
        btnDelete.setBorderPainted(false);
        btnDelete.setFocusable(false);
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDelete);

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/Actions-process-stop-icon.png"))); // NOI18N
        btnCancel.setToolTipText("Cancelar");
        btnCancel.setBorderPainted(false);
        btnCancel.setFocusable(false);
        btnCancel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnCancel);

        btnPending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/Status-user-away-icon.png"))); // NOI18N
        btnPending.setToolTipText("Ver visitas pendientes");
        btnPending.setBorderPainted(false);
        btnPending.setFocusable(false);
        btnPending.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPending.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnPending);

        btnLastAdded.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ve/com/fsjv/devsicodetv/utils/img/distributor-report-icon.png"))); // NOI18N
        btnLastAdded.setToolTipText("Ultimos agregados");
        btnLastAdded.setBorderPainted(false);
        btnLastAdded.setFocusable(false);
        btnLastAdded.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLastAdded.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnLastAdded);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 240, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddVisitor;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFindArrested;
    private javax.swing.JButton btnLastAdded;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnPending;
    private javax.swing.JButton btnSave;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnAddVisitor() {
        return btnAddVisitor;
    }

    public void setBtnAddVisitor(JButton btnAddVisitor) {
        this.btnAddVisitor = btnAddVisitor;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnEdit() {
        return btnEdit;
    }

    public void setBtnEdit(JButton btnEdit) {
        this.btnEdit = btnEdit;
    }

    public JButton getBtnFindArrested() {
        return btnFindArrested;
    }

    public void setBtnFindArrested(JButton btnFindArrested) {
        this.btnFindArrested = btnFindArrested;
    }

    public JButton getBtnLastAdded() {
        return btnLastAdded;
    }

    public void setBtnLastAdded(JButton btnLastAdded) {
        this.btnLastAdded = btnLastAdded;
    }

    public JButton getBtnNew() {
        return btnNew;
    }

    public void setBtnNew(JButton btnNew) {
        this.btnNew = btnNew;
    }

    public JButton getBtnOpen() {
        return btnOpen;
    }

    public void setBtnOpen(JButton btnOpen) {
        this.btnOpen = btnOpen;
    }

    public JButton getBtnPending() {
        return btnPending;
    }

    public void setBtnPending(JButton btnPending) {
        this.btnPending = btnPending;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public void setBtnSave(JButton btnSave) {
        this.btnSave = btnSave;
    }
}
